AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - config/**/*.rb
    - db/migrate/*.rb
    - db/schema.rb
    - db/seeds.rb
    - vendor/bundle/**/*

Metrics/LineLength:
  Max: 100

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MutableConstant:
  AutoCorrect: false

Metrics/ParameterLists:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15
  Exclude:
    - apps/**/views/**/*.rb

Metrics/BlockLength:
  Exclude:
    - apps/**/views/**/*.rb
    - spec/**/*.rb

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 7

Performance/RedundantMerge:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
